#!/bin/sh
/etc/init.d/networking restart

# exp 2
ifconfig eth0 172.16.61.1/24

# exp 3
route add -net 172.16.60.0/24 gw 172.16.61.253

# exp 4
route add default gw 172.16.61.254

# exp 5
echo 'search netlab.fe.up.pt\nnameserver 172.16.2.1' > test.txt