#!/bin/sh
/etc/init.d/networking restart

# exp 1
ifconfig eth0 172.16.60.254/24

# exp 3
ifconfig eth1 172.16.61.253/24

echo 1 > /proc/sys/net/ipv4/ip_forward
echo 0 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts

# exp 4
route add default gw 172.16.61.254

# exp 5
echo 'search netlab.fe.up.pt\nnameserver 172.16.2.1' > /etc/resolv.conf